# Generated by Django 4.2.21 on 2025-05-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
        ('oel_collections', '0005_alter_collection_options_alter_collection_enabled'),
        ('import_from_modulestore', '0002_remove_import_created_remove_import_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.learningpackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='target_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oel_collections.collection'),
        ),
    ]
