# Generated by Django 4.2.21 on 2025-05-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_from_modulestore', '0003_import_target_import_target_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import',
            old_name='override',
            new_name='override_existing_content',
        ),
        migrations.RenameField(
            model_name='import',
            old_name='user_task_status',
            new_name='task_status',
        ),
    ]
