# Generated by Django 4.2.21 on 2025-05-20 20:56

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import openedx.core.djangoapps.content_libraries.api.containers


class Migration(migrations.Migration):

    dependencies = [
        ('oel_collections', '0005_alter_collection_options_alter_collection_enabled'),
        ('oel_publishing', '0008_alter_draftchangelogrecord_options_and_more'),
        ('import_from_modulestore', '0004_rename_override_import_override_existing_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='override_existing_content',
        ),
        migrations.RemoveField(
            model_name='import',
            name='user',
        ),
        migrations.AddField(
            model_name='import',
            name='update_existing',
            field=models.BooleanField(default=False, help_text='If a piece of content already exists in the content library, should the import process update it?'),
        ),
        migrations.AlterField(
            model_name='import',
            name='composition_level',
            field=models.CharField(choices=[(openedx.core.djangoapps.content_libraries.api.containers.ContainerType['Section'], 'CHAPTER'), (openedx.core.djangoapps.content_libraries.api.containers.ContainerType['Subsection'], 'SEQUENTIAL'), (openedx.core.djangoapps.content_libraries.api.containers.ContainerType['Unit'], 'VERTICAL'), ('component', 'COMPONENT')], default='component', help_text='Maximum hierachy level at which content should be aggregated in target library', max_length=255),
        ),
        migrations.AlterField(
            model_name='import',
            name='source_key',
            field=opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, help_text='Key of the source (a course or a legacy library)', max_length=255),
        ),
        migrations.AlterField(
            model_name='import',
            name='target',
            field=models.ForeignKey(help_text='Content will be imported into this library', on_delete=django.db.models.deletion.CASCADE, to='oel_publishing.learningpackage'),
        ),
        migrations.AlterField(
            model_name='import',
            name='target_change',
            field=models.ForeignKey(help_text='Changelog entry related to this import event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oel_publishing.draftchangelog'),
        ),
        migrations.AlterField(
            model_name='import',
            name='target_collection',
            field=models.ForeignKey(help_text='Collection (within the target library) into which imported content will be grouped', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oel_collections.collection'),
        ),
    ]
