# Generated by Django 4.2.21 on 2025-05-21 23:26

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import openedx.core.djangoapps.content_libraries.api.containers


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0004_url_textfield'),
        ('oel_collections', '0005_alter_collection_options_alter_collection_enabled'),
        ('import_from_modulestore', '0005_remove_import_override_existing_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import',
            options={'verbose_name': 'ModuleStore Import', 'verbose_name_plural': 'ModuleStore Imports'},
        ),
        migrations.RemoveField(
            model_name='import',
            name='update_existing',
        ),
        migrations.AddField(
            model_name='import',
            name='replace_existing',
            field=models.BooleanField(default=False, help_text='If a piece of content already exists in the content library, should the import process replace it?'),
        ),
        migrations.AlterField(
            model_name='import',
            name='composition_level',
            field=models.CharField(choices=[('component', 'Component'), (openedx.core.djangoapps.content_libraries.api.containers.ContainerType['Unit'], 'Unit'), (openedx.core.djangoapps.content_libraries.api.containers.ContainerType['Subsection'], 'Subsection'), (openedx.core.djangoapps.content_libraries.api.containers.ContainerType['Section'], 'Section')], default='component', help_text='Maximum hierachy level at which content should be aggregated in target library', max_length=255),
        ),
        migrations.AlterField(
            model_name='import',
            name='source_key',
            field=opaque_keys.edx.django.models.LearningContextKeyField(db_index=True, help_text='Key of the content source (a course or a legacy library)', max_length=255),
        ),
        migrations.AlterField(
            model_name='import',
            name='target_collection',
            field=models.ForeignKey(help_text='Optional - Collection (within the target library) into which imported content will be grouped', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oel_collections.collection'),
        ),
        migrations.AlterField(
            model_name='import',
            name='task_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulestore_import', to='user_tasks.usertaskstatus'),
        ),
        migrations.AlterField(
            model_name='publishableentitymapping',
            name='source_usage_key',
            field=opaque_keys.edx.django.models.UsageKeyField(help_text='Original usage key of the XBlock that has been imported.', max_length=255),
        ),
    ]
