# Generated by Django 4.2.21 on 2025-05-22 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oel_collections', '0005_alter_collection_options_alter_collection_enabled'),
        ('import_from_modulestore', '0006_alter_import_options_remove_import_update_existing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='target_collection',
            field=models.ForeignKey(blank=True, help_text='Optional - Collection (within the target library) into which imported content will be grouped', null=True, on_delete=django.db.models.deletion.SET_NULL, to='oel_collections.collection'),
        ),
    ]
