# Generated by Django 4.2.21 on 2025-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_staging', '0005_stagedcontent_version_num'),
        ('import_from_modulestore', '0007_alter_import_target_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagedcontentforimport',
            old_name='import_event',
            new_name='modulestore_import',
        ),
        migrations.AlterField(
            model_name='import',
            name='composition_level',
            field=models.CharField(choices=[('component', 'Component'), ('unit', 'Unit'), ('subsection', 'Subsection'), ('section', 'Section')], default='component', help_text='Maximum hierachy level at which content should be aggregated in target library', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='stagedcontentforimport',
            unique_together={('modulestore_import', 'staged_content')},
        ),
    ]
