# Generated by Django 4.2.21 on 2025-05-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_from_modulestore', '0008_rename_import_event_stagedcontentforimport_modulestore_import_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishableentityimport',
            old_name='import_event',
            new_name='modulestore_import',
        ),
        migrations.AlterUniqueTogether(
            name='publishableentityimport',
            unique_together={('modulestore_import', 'resulting_mapping')},
        ),
    ]
